# Generated by Django 3.1.4 on 2021-01-15 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('agents', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='behaviourrepomodel',
            name='b_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='agents.behaviourrepositorymodel'),
        ),
        migrations.AddField(
            model_name='behaviourrepomodel',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentrepomodel',
            name='a_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='agents.agentrepositorymodel'),
        ),
        migrations.AddField(
            model_name='agentrepomodel',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='agents',
            field=models.ManyToManyField(through='accounts.AgentRepoModel', to='agents.AgentRepositoryModel'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='behaviours',
            field=models.ManyToManyField(through='accounts.BehaviourRepoModel', to='agents.BehaviourRepositoryModel'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
