# Generated by Django 3.1.4 on 2020-12-20 09:31

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConfigsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('extend', models.TextField(default='{}')),
                ('is_base', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'db_table': 'agent_configs',
            },
        ),
        migrations.CreateModel(
            name='BehaviourConfigsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('is_progress_pool', models.BooleanField(default=False)),
                ('default_pool_size', models.IntegerField(default=5)),
                ('extend', models.TextField(default='{}')),
                ('is_base', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'db_table': 'behaviour_configs',
            },
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('parent', models.IntegerField(default=0)),
                ('type', models.SmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='VersionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('previous', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'version',
            },
        ),
        migrations.CreateModel(
            name='InitialAgentsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('behaviours', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('basic_agent', models.IntegerField()),
                ('credit', models.CharField(db_index=True, max_length=100)),
                ('agent_category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='agent_initial_category', to='agents.categorymodel')),
                ('agent_configs', models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='agents.agentconfigsmodel')),
                ('behaviour_configs', models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='agents.behaviourconfigsmodel')),
                ('belong_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_initial_agent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'initial_agents',
            },
        ),
        migrations.CreateModel(
            name='BehavioursModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('prerequisite_behaviour_categories', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('prerequisite_agents', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('parent_behaviour', models.IntegerField(blank=True, default=None, null=True)),
                ('url', models.URLField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_office', models.BooleanField(db_index=True, default=False, verbose_name='office or user defined')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user_behaviours', to=settings.AUTH_USER_MODEL)),
                ('behaviour_category', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='agents.categorymodel')),
                ('configs', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='config_behaviours', to='agents.behaviourconfigsmodel')),
            ],
            options={
                'db_table': 'behaviours',
            },
        ),
        migrations.CreateModel(
            name='BasicAgentsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('prerequisite_behaviour_categories', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('default_behaviours', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('parent_agent', models.IntegerField(blank=True, db_index=True, default=None, null=True)),
                ('url', models.URLField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_office', models.BooleanField(db_index=True, default=False, verbose_name='office or user defined')),
                ('in_docker', models.BooleanField(db_index=True, default=False, verbose_name='docker exist or not')),
                ('extra_support_version', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('agent_category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='agent_basic_category', to='agents.categorymodel')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user_basic_agent', to=settings.AUTH_USER_MODEL)),
                ('configs', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='config_agents', to='agents.agentconfigsmodel')),
                ('version', models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='agents.versionmodel')),
            ],
            options={
                'db_table': 'basic_agents',
            },
        ),
    ]
